### ISSUE TITLE
小白提出的提问，关于cannot import name 'evalcontextfilter' from 'jinja2' 的问题

### ISSUE THREAD

**Issue by MapleleavesQY** [Aues6uen11Z/HonkaiHelper#1]
Traceback (most recent call last):
  File "D:\Github\HONKAI\HonkaiHelper\main.py", line 8, in <module>
    from airtest.cli.parser import cli_setup
  File "C:\Users\Mapleleaves\AppData\Local\Programs\Python\Python39\lib\site-packages\airtest\cli\parser.py", line 4, in <module>
    from airtest.report.report import get_parger as report_parser
  File "C:\Users\Mapleleaves\AppData\Local\Programs\Python\Python39\lib\site-packages\airtest\report\report.py", line 15, in <module>
    from jinja2 import evalcontextfilter, Markup, escape
ImportError: cannot import name 'evalcontextfilter' from 'jinja2' (C:\Users\Mapleleaves\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\__init__.py)

在电脑上尝试部署后出现如下提示，google百度均无果，故提问大佬
小白一个，求大佬不要生气

**Comment by Aues6uen11Z** [comment]
我看网上说这样可能是jinja2版本过高需要降到2.x，但我自己也是3.x版本所以不太清楚。可以pip list看一下吗？

**Comment by MapleleavesQY** [comment]
以下是pip list截取的jinja2的部分：

idna                    3.3
ixml                    0.1.0
Jinja2                  3.1.1
kiwisolver              1.3.2
lxml                    4.6.2
MarkupSafe              2.1.1
matplotlib              3.5.1
mss                     6.1.0
multidict               6.0.2

似乎我的是3.1.1的，我去尝试一下降版本再试试吧

**Comment by MapleleavesQY** [comment]
我的问题已经解决，除了将版本更新为2.8以上但3.0以下外（本人使用3.8python版本），有可能还会出现如下报错：
ImportError: cannot import name ‘soft_unicode‘ from ‘markupsafe‘

解决方法也是版本问题：

python -m pip install markupsafe==2.0.1

感谢大佬指点~~我关贴啦~

**Comment by Aues6uen11Z** [comment]
我也没有帮到什么忙(ಥ_ಥ)，问题解决了就好。脚本写的比较烂，如果对你有用就太好啦~
