### ISSUE TITLE
有一点问题

### ISSUE THREAD

**Issue by fengqui** [Aues6uen11Z/HonkaiHelper#12]
脚本启动了一会，脚本界面就自动关闭了，崩坏只是签到就没了。

**Comment by Aues6uen11Z** [comment]
是不是卡在月卡界面了，网页报告里有报错吗？

**Comment by fengqui** [comment]
没有网页报告，只有log.txt,不是卡在月卡上，好像是卡在点左上角的名字上

**Comment by Aues6uen11Z** [comment]
可以手动执行下main.py里的simple_report()生成报告，或者用AirtestIDE左上角 运行->打开报告目录 生成。等我有空了再把日志这完善下，现在比较简陋。

**Comment by fengqui** [comment]
行行
