### ISSUE TITLE
点开任务就闪退了

### ISSUE THREAD

**Issue by SanJin-X** [Aues6uen11Z/HonkaiHelper#13]
最开始是全屏，显示识别不到，我就改成1280×720窗口模式，变成闪退了
<img width="1274" alt="{F41EBFF4-C4E2-4b27-AF8E-B9D553BCC535}" src="https://github.com/Aues6uen11Z/HonkaiHelper/assets/116250673/7ff73a6a-916c-4975-97bd-dcb7355f6d02">

**Comment by liminyi1024** [comment]
相同问题截取到的错误代码。
![cuowu](https://github.com/Aues6uen11Z/HonkaiHelper/assets/74053330/b8b15bbb-448d-4fb3-91a6-a561fd14ac03)

**Comment by Aues6uen11Z** [comment]
pponnxcr升级把变量名改了，先降级使用吧，最近比较忙回头再改我的代码
pip install pponnxcr==2.0

另外有个依赖包只支持到python3.9，用3.12不知道会有什么问题，不过你可以替我先试试，有问题我再看能不能改

**Comment by SanJin-X** [comment]
目前基本能用，但是逻辑上似乎有些问题，应该要先减负再挂远征
还有几个小问题
1.打工界面会卡在刷新
2.远征只会挂第一个，次数不够了之后不会选择下一个继续挂远征
3.还是会卡领取界面
<img width="744" alt="{1BBB548A-2197-4f3e-BC92-DB6434BD4FD8}" src="https://github.com/Aues6uen11Z/HonkaiHelper/assets/116250673/c8da72f4-bedb-4082-9005-3291bcf6e151">

**Comment by Aues6uen11Z** [comment]
先减负再远征有可能体力不够用，我的考虑是尽可能挂远征收材料，减负只为了完成活跃任务。
1. 打工卡刷新这个我没遇到过，而且我看半天也没发现有哪里同时会识别到“刷新，始打工”，可以提供一下游戏截图吗？
2. 这个我确实没考虑到，我平常刷的黑核不会次数不够。。。
3. 哪个领取界面可以截下图吗？

**Comment by SanJin-X** [comment]
鼠标会锁在刷新的位置不动
<img width="642" alt="{4EE1FBA8-653B-4f9a-ADD7-8DAFE46CDCDE}" src="https://github.com/Aues6uen11Z/HonkaiHelper/assets/116250673/470ecc41-4018-44be-809a-7238b5f52dc9">
可能是我今天做完了活跃任务？有时候就会卡在任务界面，触发条件也不太清楚，要我手动点返回或者主菜单才会继续进行
<img width="643" alt="{6F52057F-60C4-4f62-9717-F53C72C25638}" src="https://github.com/Aues6uen11Z/HonkaiHelper/assets/116250673/78c7e20c-f4f1-40f9-9c60-79c4c6ebb87f">
