### ISSUE TITLE
任务领取界面

### ISSUE THREAD

**Issue by SanJin-X** [Aues6uen11Z/HonkaiHelper#15]
1.家园打工界面选择的是第二个派遣任务，而不是第一个
2.活跃奖励领取界面最后会点击一个任务详情，这里应该是要领取活跃奖励的
<img width="644" alt="微信图片_20240405125510" src="https://github.com/Aues6uen11Z/HonkaiHelper/assets/116250673/6b38f291-5876-4b2b-85a6-b44340799eee">

**Comment by Aues6uen11Z** [comment]
请附上日志，或者等过段时间我改进完报告再提bug，现在在写界面

**Comment by Aues6uen11Z** [comment]
你的窗口看上去和我不太一样，是Win11吗？如果是可能是窗口边界和我Win10不一样导致的问题，你可以打开崩三窗口调到720P后，自己新建个python文件执行这段代码看看结果是不是 (754, 1286, 3)
```python
from zafkiel.device.api import API


API().auto_setup(devices=["WindowsPlatform:///?title=崩坏3", ])
img = API().screenshot()
print(img.shape)
```

**Comment by SanJin-X** [comment]
<img width="867" alt="微信图片_20240507001153" src="https://github.com/Aues6uen11Z/HonkaiHelper/assets/116250673/35aea5f8-4466-45bc-a35e-54b06ca75764">
电脑是win11

**Comment by Aues6uen11Z** [comment]
这个结果有点离谱了啊🧐，游戏分辨率是1280*720吗？

**Comment by SanJin-X** [comment]
今天和昨天还不一样
<img width="876" alt="{96F816C3-CA1D-45e9-9744-A9E3A4094F9B}" src="https://github.com/Aues6uen11Z/HonkaiHelper/assets/116250673/2ac21998-511b-4691-abd9-df8377010a20">

**Comment by Aues6uen11Z** [comment]
确实不一样，你试试在HonkaiHelper/config.py里加一句，看还会不会有点错地方的情况
```python
Config.BORDER = (38, 3, 2)
```
这个边框大小我没研究过，后面应该还是用点靠谱的方法来获取数值，而不是这样直接设置=.=

**Comment by Aues6uen11Z** [comment]
边框问题已在Zafkiel-0.1.2修复，更新后可以把自己的设置删掉了
