### ISSUE TITLE
找不到家园按钮

### ISSUE THREAD

**Issue by ssrshiwode** [Aues6uen11Z/HonkaiHelper#16]
win11系统，无法找到右下角的家园按钮。
![image](https://github.com/Aues6uen11Z/HonkaiHelper/assets/42463699/9165dbe0-e08d-4ab1-87a5-c68212099d64)
![image](https://github.com/Aues6uen11Z/HonkaiHelper/assets/42463699/e357df58-b937-4fed-9eec-ebf2d462f02a)
[log.txt](https://github.com/Aues6uen11Z/HonkaiHelper/files/15235977/log.txt)

**Comment by Aues6uen11Z** [comment]
先试试把 设置-辅助-显示菜单提示 关闭，如果还不行再试试这个吧
https://github.com/Aues6uen11Z/HonkaiHelper/issues/15#issuecomment-2097354938

**Comment by ssrshiwode** [comment]
> 先试试把 设置-辅助-显示菜单提示 关闭，如果还不行再试试这个吧 [#15 (comment)](https://github.com/Aues6uen11Z/HonkaiHelper/issues/15#issuecomment-2097354938)

设置-辅助-显示菜单提示 关闭就可以点到家园按钮了，感谢😊
