### ISSUE TITLE
能识别到作战任务的一键领取按钮，但是不点击按钮

### ISSUE THREAD

**Issue by ssrshiwode** [Aues6uen11Z/HonkaiHelper#17]
win11，125%缩放，2k全屏
流程跑完无报错，但是一键领取按钮总是点不到
![image](https://github.com/Aues6uen11Z/HonkaiHelper/assets/42463699/9116748a-63e3-42c1-babd-ce02b030aec5)
![image](https://github.com/Aues6uen11Z/HonkaiHelper/assets/42463699/e3513bfe-28dd-43f9-bf2b-28d3c0384fac)
[log.txt](https://github.com/Aues6uen11Z/HonkaiHelper/files/15274430/log.txt)

**Comment by Aues6uen11Z** [comment]
这个有点看不出原因，我之前好像也遇到过，不行就先用720P吧

**Comment by ssrshiwode** [comment]
全屏会点不到 一键领取 按钮，切换成 1920*1080有边框就可以点到 一键领取 按钮了
