### ISSUE TITLE
适配多屏

### ISSUE THREAD

**Issue by Zhuazizizi** [Aues6uen11Z/HonkaiHelper#19]
可以对多屏幕的情况进行适配吗，目前我在有副屏的情况下使用时点击的位置是不准的，拔掉副屏的话是正常的

**Comment by Aues6uen11Z** [comment]
我目前没有多余屏幕可供测试，暂时没法适配，不过欢迎自行探索可能的原因和解决办法，我会尽可能提供协助

**Comment by Zhuazizizi** [comment]
> 我目前没有多余屏幕可供测试，暂时没法适配，不过欢迎自行探索可能的原因和解决办法，我会尽可能提供协助

本来在想用手机做无线显示器不知道环境效果会不会一样，今天突然副屏烧了，这下好了，不用整了（

**Comment by Aues6uen11Z** [comment]
![24eddea4b46cddd1a4d97ff495cef21d](https://github.com/user-attachments/assets/0af74874-4dc2-4d26-ad25-eaecd8429ebd)
