### ISSUE TITLE
这是啥问题

### ISSUE THREAD

**Issue by Zq-xiaoshixiaozhi** [Aues6uen11Z/HonkaiHelper#21]
[dacapo.log](https://github.com/user-attachments/files/17083006/dacapo.log)
[dacapo.log](https://github.com/user-attachments/files/17083007/dacapo.log)

更新报错

**Comment by Aues6uen11Z** [comment]
更新报错是我克隆成Github仓库了，现在换成Gitee的了，重新下发布包或自己也手动换下也行
运行报错应该是你没填游戏路径
