### ISSUE TITLE
无法使用,并报错

### ISSUE THREAD

**Issue by libaiqwq** [Aues6uen11Z/HonkaiHelper#22]
[dacapo.log](https://github.com/user-attachments/files/17084663/dacapo.log)

**Comment by libaiqwq** [comment]
附图
![image](https://github.com/user-attachments/assets/d6792fc1-f5c6-4a2c-9f2a-6593f01d5d75)

**Comment by libaiqwq** [comment]
附尝试停止时图
![image](https://github.com/user-attachments/assets/93969220-1fda-4636-9a5b-96866ac87aba)

**Comment by Aues6uen11Z** [comment]
正在修这个bug，不过这里应该只是你没填游戏路径，填上就好了

**Comment by libaiqwq** [comment]
填了的，只是没附上图，并且这个问题与游戏路径无关，我测试了填地址与不填地址，都会报错

**Comment by Aues6uen11Z** [comment]
这个报错是nuitka打包后出现的，我源码运行没问题，不知道为什么打包后子进程的stdout是GB2312编码。
如果不是游戏路径的问题，那修好这个还是有别的问题了==

**Comment by libaiqwq** [comment]
希望大佬没事吧，这几天不方便使用电脑，没法提供有/无路径的日志
，抱歉XwX

**Comment by Aues6uen11Z** [comment]
编码bug已修，重新下载看看报错内容是啥
