### ISSUE TITLE
一直报错，用不了

### ISSUE THREAD

**Issue by sonicfire** [Aues6uen11Z/HonkaiHelper#23]
[log.txt](https://github.com/user-attachments/files/17107473/log.txt)

能启动到主界面但是只能点几下，一直报错

**Comment by sonicfire** [comment]
![屏幕截图 2024-09-24 113952](https://github.com/user-attachments/assets/36212a1d-97fa-41de-8577-cf117150aa06)

**Comment by sonicfire** [comment]
查了一下，是图包有问题，舰桥版本不对以及一些图过时了。自己更新截图部分可用。

**Comment by Aues6uen11Z** [comment]
怪，我前天用还挺正常的，怎么版本更新完了还能突然变，等我晚上回去看看

**Comment by avicid** [comment]
大佬们都用哪个舰桥啊，我用车站舰桥不行

**Comment by sonicfire** [comment]
我自己调整了一下，大部分功能都可以了。但是BP奖励那边不行，好像是那个dairy_bP数值读不出来。
一键领取奖励以后就停在那里了。上面的图应该可以看出记录。

**Comment by sonicfire** [comment]
已测试，一切正常。
另外，我能不能设置结束后不退出游戏？

**Comment by Aues6uen11Z** [comment]
可以试试手动把“退出游戏”任务移除
