### ISSUE TITLE
Download .NET Framework 4.8.1 文件缺失

### ISSUE THREAD

**Issue by qincenhua** [Aues6uen11Z/HonkaiHelper#24]
无法运行

**Comment by qincenhua** [comment]
https://github.com/user-attachments/assets/e3363a01-1099-4318-acd4-3251a931b8c9

**Comment by qincenhua** [comment]
有没有QQ群呀?想问一下群友怎么解决/exe什么时候出一个安装包安装就能在桌面双击程序运行而不是解压出来

**Comment by Aues6uen11Z** [comment]
没有群呢，文件缺失可能要自己安装下对应的东西，还有看视频你是win7？win10以下不能保证正常运行

**Comment by qincenhua** [comment]
建立桌面快捷方式会更快捷在文件里面去找有些人真的会找了半天不知道哪个是启动的exe这个应用程序在桌面方便更快捷建议尽快开发

**Comment by Aues6uen11Z** [comment]
@qincenhua 
1. 我不太懂python怎么打包成安装包形式，如果你有想法可以pr。我个人精力有限，暂时不想开群
2. 现在清体力本来就是一键减负了，至于深渊乐土短时间内不是很有动力
3. 不会开发任何有关做主线做剧情的功能
4. 精力有限，个人不会维护win10以下版本
5. 可以自己创建这个exe的快捷方式啊
