### ISSUE TITLE
运行问题如图

### ISSUE THREAD

**Issue by qincenhua** [Aues6uen11Z/HonkaiHelper#25]
![Image_1729785418395](https://github.com/user-attachments/assets/7ab8ac15-1ef8-40dd-adab-a048ccc0eb69)
![Image_1729785390976](https://github.com/user-attachments/assets/2762ef5e-8204-41c2-bac2-2eeed2e78ec8)
![Image_1729784400772](https://github.com/user-attachments/assets/d43195a3-0204-4d2c-88a6-fbfb212d5a06)
![Image_1729784072131](https://github.com/user-attachments/assets/84cb1758-5fa1-457b-b9e0-401a297c70ac)
![Image_1729782518566](https://github.com/user-attachments/assets/113a54b1-338f-4b33-b83a-27560b1c2764)
运行问题

**Comment by Aues6uen11Z** [comment]
要么关了游戏再运行，要么开着游戏把“启动游戏”任务移除
权限不足按理说是不会出现的，不知道你改了什么
最后一个又像是没填游戏路径
总之说清楚点啊，就几张图也没个前因后果
