### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by X-Zero-L** [Aues6uen11Z/HonkaiHelper#4]
使用脚本启动游戏，登录进游戏后，会在舰上不断重复退出游戏->取消->退出游戏->取消,这是为什么呢，分辨率是设置1280×720窗口模式
![image](https://user-images.githubusercontent.com/98764734/180934606-5bf69fb5-8834-4d7f-ac71-f65a87bbda17.png)
![image](https://user-images.githubusercontent.com/98764734/180934619-5cafef99-328e-4c38-85e2-a5b7f211fbaa.png)
就是像图上这样，会不断重复

**Comment by Aues6uen11Z** [comment]
你不是今天第一次登录吧？这应该是在找签到按钮，不过超时也会自动往下进行

**Comment by X-Zero-L** [comment]
好的，知道了☺
