### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by aluxiaofei** [Aues6uen11Z/HonkaiHelper#6]
修改设置之后，出现下面的错误，该如何解决？
Traceback (most recent call last):
  File "E:\A\HonkaiHelper-master\main.py", line 5, in <module>
    from airtest.cli.parser import cli_setup
ModuleNotFoundError: No module named 'airtest'

**Comment by Aues6uen11Z** [comment]
百度如何安装python包，把airtest装上

**Comment by Aues6uen11Z** [comment]
这个我也没遇到过，自己查一下吧=.=
