### ISSUE TITLE
建议添加一个在崩溃后按下任意键继续的功能

### ISSUE THREAD

**Issue by uf-hy** [Aues6uen11Z/HonkaiHelper#7]
感谢你做的自动化脚本, 我在使用过程中偶尔会遇到些环境相关的bug,如"DLL load failed while importing win32api: 找不到指定的程序"等, 
但是在崩溃时错误信息转瞬即逝, 目前我的做法是用录屏软件来录屏逐帧回放查看错误信息再结合搜索引擎debug, 想问一下能不能在非正常退出/崩溃时添加一个按下任意键继续的功能, 方便查看错误信息.

**Comment by Aues6uen11Z** [comment]
按理说在IDE里运行应该能看见报错，如果用命令行你可以先试试cmd /k或者pause
